export { proyectosService } from './proyectosService'
export { tipologiasService } from './tipologiasService'
export { imagenesProyectoService } from './imagenesProyectoService'
export { imagenesTipologiaService } from './imagenesTipologiaService'
export { equipamientoService } from './equipamientoService'
export { catalogoService } from './catalogoService'
